# Generated by Django 5.1.1 on 2024-10-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnA', models.CharField(max_length=255)),
                ('columnB', models.FloatField()),
            ],
        ),
    ]
