# Generated by Django 5.1.1 on 2024-10-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datavisualizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('student_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('answers', models.TextField()),
                ('correct_answers', models.TextField()),
                ('question_number', models.IntegerField()),
                ('subject_contents', models.TextField()),
                ('assessment_areas', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SampleModel1',
        ),
        migrations.DeleteModel(
            name='SampleModel2',
        ),
    ]
